<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-27T01:43:42 EDT" name="Suite" finished-at="2024-05-27T01:43:58 EDT" duration-ms="16479">
    <groups>
    </groups>
    <test started-at="2024-05-27T01:43:42 EDT" name="Test" finished-at="2024-05-27T01:43:58 EDT" duration-ms="16479">
      <class name="com.shivani.Demo1">
        <test-method is-config="true" signature="open_the_chrome_and_launch_fb()[pri:0, instance:com.shivani.Demo1@4f209819]" started-at="2024-05-27T01:43:42 EDT" name="open_the_chrome_and_launch_fb" finished-at="2024-05-27T01:43:46 EDT" duration-ms="4018" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- open_the_chrome_and_launch_fb -->
        <test-method signature="connect_to_db()[pri:0, instance:com.shivani.Demo1@4f209819]" started-at="2024-05-27T01:43:46 EDT" name="connect_to_db" finished-at="2024-05-27T01:43:47 EDT" duration-ms="646" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- connect_to_db -->
        <test-method signature="enter_username_and_password()[pri:0, instance:com.shivani.Demo1@4f209819]" started-at="2024-05-27T01:43:47 EDT" name="enter_username_and_password" finished-at="2024-05-27T01:43:53 EDT" duration-ms="5979" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- enter_username_and_password -->
        <test-method signature="user_login_successful()[pri:0, instance:com.shivani.Demo1@4f209819]" started-at="2024-05-27T01:43:53 EDT" name="user_login_successful" finished-at="2024-05-27T01:43:53 EDT" duration-ms="510" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Facebook] but found [(2) Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Facebook] but found [(2) Facebook]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.shivani.Demo1.user_login_successful(Demo1.java:86)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- user_login_successful -->
        <test-method is-config="true" signature="browser_quit()[pri:0, instance:com.shivani.Demo1@4f209819]" started-at="2024-05-27T01:43:53 EDT" name="browser_quit" finished-at="2024-05-27T01:43:58 EDT" duration-ms="5273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browser_quit -->
      </class> <!-- com.shivani.Demo1 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
